# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Predation <- function(time, site, x, u, f) {
    .Call(`_migrationSDP_Predation`, time, site, x, u, f)
}

Init <- function(MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend, penalty) {
    invisible(.Call(`_migrationSDP_Init`, MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend, penalty))
}

BackwardIteration <- function() {
    .Call(`_migrationSDP_BackwardIteration`)
}

InitSim <- function(MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend) {
    invisible(.Call(`_migrationSDP_InitSim`, MinT, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, y_gain, y_expend))
}

simForaging <- function(f_intensity, time, site, x) {
    .Call(`_migrationSDP_simForaging`, f_intensity, time, site, x)
}

simFlying <- function(decision, time, site, x) {
    .Call(`_migrationSDP_simFlying`, decision, time, site, x)
}

