# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Flying <- function(time, site, x, dep_site) {
    .Call(`_migrationSDP_Flying`, time, site, x, dep_site)
}

Init <- function(MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, x_gain, y_gain, p_gain, expend) {
    invisible(.Call(`_migrationSDP_Init`, MaxT, NSites, MaxX, w, xc, B0, b0, b1, b2, pred_a1, pred_a2, c, speed, WindAssist, WindProb, ZStdNorm, PStdNorm, nTR_x, nTR_y, decError, dist, bear, x_gain, y_gain, p_gain, expend))
}

BackwardIteration <- function() {
    .Call(`_migrationSDP_BackwardIteration`)
}

